export const KolkataLocality = [
    { value:'Agarpara', label:'Agarpara'},
    { value:'AJC Bose Road', label:'AJC Bose Road'},
    { value:'Ajoy Nagar', label:'Ajoy Nagar'},
    { value:'Alambazar', label:'Alambazar'},
    { value:'Alipore', label:'Alipore'},
    { value:'Alipur Road', label:'Alipur Road'},
    { value:'Amtala', label:'Amtala'},
    { value:'Amtala-Baruipur Road', label:'Amtala-Baruipur Road'},
    { value:'Anandpur', label:'Anandpur'},
    { value:'Andharmanik', label:'Andharmanik'},
    { value:'Andul Road', label:'Andul Road'},
    { value:'APC Road', label:'APC Road'},
    { value:'Arambagh', label:'Arambagh'},
    { value:'Ariadaha', label:'Ariadaha'},
    { value:'Ashok Nagar', label:'Ashok Nagar'},
    { value:'Atapara', label:'Atapara'},
    { value:'B B D Bagh', label:'B B D Bagh'},
    { value:'B L Saha Road', label:'B L Saha Road'},
    { value:'Bablatala', label:'Bablatala'},
    { value:'Badartala', label:'Badartala'},
    { value:'Bagbazar', label:'Bagbazar'},
    { value:'Baghajatin', label:'Baghajatin'},
    { value:'Bagmari', label:'Bagmari'},
    { value:'Baguiati', label:'Baguiati'},
    { value:'Baidyabati', label:'Baidyabati'},
    { value:'Bakhrahat Road', label:'Bakhrahat Road'},
    { value:'Bakkhali', label:'Bakkhali'},
    { value:'Bakultala', label:'Bakultala'},
    { value:'Bally', label:'Bally'},
    { value:'Ballygunge', label:'Ballygunge'},
    { value:'Bamangachi', label:'Bamangachi'},
    { value:'Bandel', label:'Bandel'},
    { value:'Bangur', label:'Bangur'},
    { value:'Bankra', label:'Bankra'},
    { value:'Bansdroni', label:'Bansdroni'},
    { value:'Bantala', label:'Bantala'},
    { value:'Bara Bazar', label:'Bara Bazar'},
    { value:'Baranagar', label:'Baranagar'},
    { value:'Barasat', label:'Barasat'},
    { value:'Barasat', label:'Barasat'},
    { value:'Barisha', label:'Barisha'},
    { value:'Barrackpore', label:'Barrackpore'},
    { value:'Baruipur', label:'Baruipur'},
    { value:'Basirhat', label:'Basirhat'},
    { value:'Batanagar', label:'Batanagar'},
    { value:'BBT Road', label:'BBT Road'},
    { value:'Beck Bagan', label:'Beck Bagan'},
    { value:'Bedibhawan', label:'Bedibhawan'},
    { value:'Behala', label:'Behala'},
    { value:'Belgachia', label:'Belgachia'},
    { value:'Belgharia', label:'Belgharia'},
    { value:'Beliaghata', label:'Beliaghata'},
    { value:'Belur', label:'Belur'},
    { value:'Beniapukur', label:'Beniapukur'},
    { value:'Beniatola', label:'Beniatola'},
    { value:'Berunanpukhuria', label:'Berunanpukhuria'},
    { value:'Bhadreswar', label:'Bhadreswar'},
    { value:'Bhowanipore', label:'Bhowanipore'},
    { value:'Bibirhat', label:'Bibirhat'},
    { value:'Bidhannagar', label:'Bidhannagar'},
    { value:'Bidhanpally', label:'Bidhanpally'},
    { value:'Bijoygarh', label:'Bijoygarh'},
    { value:'Bikramgarh', label:'Bikramgarh'},
    { value:'Birati', label:'Birati'},
    { value:'Biren Roy Road West', label:'Biren Roy Road West'},
    { value:'Birlapur', label:'Birlapur'},
    { value:'Bishnupur', label:'Bishnupur'},
    { value:'Bondel Road', label:'Bondel Road'},
    { value:'Bongaon', label:'Bongaon'},
    { value:'Bonhooghly', label:'Bonhooghly'},
    { value:'Boral', label:'Boral'},
    { value:'Bowbazar', label:'Bowbazar'},
    { value:'Brahmapur', label:'Brahmapur'},
    { value:'BT Road', label:'BT Road'},
    { value:'Budge Budge', label:'Budge Budge'},
    { value:'Budge Budge Road', label:'Budge Budge Road'},
    { value:'Burdwan Road', label:'Burdwan Road'},
    { value:'Buroshibtalla', label:'Buroshibtalla'},
    { value:'Canning', label:'Canning'},
    { value:'Chakdaha', label:'Chakdaha'},
    { value:'Champahati', label:'Champahati'},
    { value:'Champdani', label:'Champdani'},
    { value:'Chandannagar', label:'Chandannagar'},
    { value:'Chandni Chowk', label:'Chandni Chowk'},
    { value:'Chetla', label:'Chetla'},
    { value:'Chinar Park', label:'Chinar Park'},
    { value:'Chingrighata', label:'Chingrighata'},
    { value:'Chitpur', label:'Chitpur'},
    { value:'Chowbaga', label:'Chowbaga'},
    { value:'Chowringhee', label:'Chowringhee'},
    { value:'College Street', label:'College Street'},
    { value:'Cossipore', label:'Cossipore'},
    { value:'Dakshindari', label:'Dakshindari'},
    { value:'Dakshineswar', label:'Dakshineswar'},
    { value:'Dankuni', label:'Dankuni'},
    { value:'Dasnagar', label:'Dasnagar'},
    { value:'Dhakuria', label:'Dhakuria'},
    { value:'Dhamua', label:'Dhamua'},
    { value:'Dhapa', label:'Dhapa'},
    { value:'Dharmatala', label:'Dharmatala'},
    { value:'Diamond Harbour Road', label:'Diamond Harbour Road'},
    { value:'Domjur', label:'Domjur'},
    { value:'Dum Dum', label:'Dum Dum'},
    { value:'Dum Dum Cantt', label:'Dum Dum Cantt'},
    { value:'Dum Dum Park', label:'Dum Dum Park'},
    { value:'Dum Dum Road', label:'Dum Dum Road'},
    { value:'Dunlop', label:'Dunlop'},
    { value:'Durga Nagar', label:'Durga Nagar'},
    { value:'Duttapukur', label:'Duttapukur'},
    { value:'E.M. Bypass', label:'E.M. Bypass'},
    { value:'East Kolkata Township', label:'East Kolkata Township'},
    { value:'Elgin', label:'Elgin'},
    { value:'EM Bypass', label:'EM Bypass'},
    { value:'EM Bypass Connector', label:'EM Bypass Connector'},
    { value:'Entally', label:'Entally'},
    { value:'Feeder Road', label:'Feeder Road'},
    { value:'G.T. Road', label:'G.T. Road'},
    { value:'Ganganagar', label:'Ganganagar'},
    { value:'Ganguli Bagan', label:'Ganguli Bagan'},
    { value:'Garcha', label:'Garcha'},
    { value:'Garden Reach', label:'Garden Reach'},
    { value:'Garfa', label:'Garfa'},
    { value:'Garia', label:'Garia'},
    { value:'Gariahat', label:'Gariahat'},
    { value:'Ghosh Para Road', label:'Ghosh Para Road'},
    { value:'Ghuni', label:'Ghuni'},
    { value:'Ghusuri', label:'Ghusuri'},
    { value:'Gobra', label:'Gobra'},
    { value:'Godkhali', label:'Godkhali'},
    { value:'Golaghata', label:'Golaghata'},
    { value:'Golf Green', label:'Golf Green'},
    { value:'Golpark', label:'Golpark'},
    { value:'Guptipara', label:'Guptipara'},
    { value:'Habra', label:'Habra'},
    { value:'Haldia', label:'Haldia'},
    { value:'Halisahar', label:'Halisahar'},
    { value:'Haltu', label:'Haltu'},
    { value:'Haridevpur', label:'Haridevpur'},
    { value:'Harinavi', label:'Harinavi'},
    { value:'Haringhata', label:'Haringhata'},
    { value:'Harish Mukherjee Road', label:'Harish Mukherjee Road'},
    { value:'Hasnabad', label:'Hasnabad'},
    { value:'Hastings', label:'Hastings'},
    { value:'Hati Bagan', label:'Hati Bagan'},
    { value:'Hatiara', label:'Hatiara'},
    { value:'Hatiara Road', label:'Hatiara Road'},
    { value:'Hatkhola', label:'Hatkhola'},
    { value:'Hazra', label:'Hazra'},
    { value:'Hazra Road', label:'Hazra Road'},
    { value:'Hindustan Park', label:'Hindustan Park'},
    { value:'Hooghly', label:'Hooghly'},
    { value:'Howrah', label:'Howrah'},
    { value:'Hridaypur', label:'Hridaypur'},
    { value:'Ichapur', label:'Ichapur'},
    { value:'Jadavpur', label:'Jadavpur'},
    { value:'Jagatdal', label:'Jagatdal'},
    { value:'Jagatipota', label:'Jagatipota'},
    { value:'Jalkal', label:'Jalkal'},
    { value:'James Long Sarani', label:'James Long Sarani'},
    { value:'Jawpur', label:'Jawpur'},
    { value:'Jessore Road', label:'Jessore Road'},
    { value:'Jharkhali', label:'Jharkhali'},
    { value:'Jodhpur Park', label:'Jodhpur Park'},
    { value:'Joka', label:'Joka'},
    { value:'Jorabagan', label:'Jorabagan'},
    { value:'Jorasanko', label:'Jorasanko'},
    { value:'Julpia', label:'Julpia'},
    { value:'Kaikhali', label:'Kaikhali'},
    { value:'Kalighat', label:'Kalighat'},
    { value:'Kalikapur', label:'Kalikapur'},
    { value:'Kalikapur-New Town', label:'Kalikapur-New Town'},
    { value:'Kalikapur-Rajpur Sonarpur', label:'Kalikapur-Rajpur Sonarpur'},
    { value:'Kalitala', label:'Kalitala'},
    { value:'Kalyani', label:'Kalyani'},
    { value:'Kamalgazi', label:'Kamalgazi'},
    { value:'Kamarpukur', label:'Kamarpukur'},
    { value:'Kamdahari', label:'Kamdahari'},
    { value:'Kanchrapara', label:'Kanchrapara'},
    { value:'Kankurgachi', label:'Kankurgachi'},
    { value:'Karimpur', label:'Karimpur'},
    { value:'Kasba', label:'Kasba'},
    { value:'Kashipur', label:'Kashipur'},
    { value:'Kazipara', label:'Kazipara'},
    { value:'Keshtopur', label:'Keshtopur'},
    { value:'Khanna', label:'Khanna'},
    { value:'Khardaha', label:'Khardaha'},
    { value:'Khariberia', label:'Khariberia'},
    { value:'Kheyadah', label:'Kheyadah'},
    { value:'Khidirpur', label:'Khidirpur'},
    { value:'Kona Expressway', label:'Kona Expressway'},
    { value:'Konnagar', label:'Konnagar'},
    { value:'Krishnapur', label:'Krishnapur'},
    { value:'Kudghat', label:'Kudghat'},
    { value:'Kulerdari', label:'Kulerdari'},
    { value:'Kustia', label:'Kustia'},
    { value:'Lake Gardens', label:'Lake Gardens'},
    { value:'Lake Market', label:'Lake Market'},
    { value:'Lake Town', label:'Lake Town'},
    { value:'Laskarpur', label:'Laskarpur'},
    { value:'Liluah', label:'Liluah'},
    { value:'Machuabazar', label:'Machuabazar'},
    { value:'Madhyamgram', label:'Madhyamgram'},
    { value:'Madurdaha', label:'Madurdaha'},
    { value:'Maharsi Debendra Road', label:'Maharsi Debendra Road'},
    { value:'Mahatma Gandhi Road', label:'Mahatma Gandhi Road'},
    { value:'Maheshtala', label:'Maheshtala'},
    { value:'Mahishgote', label:'Mahishgote'},
    { value:'Maidan', label:'Maidan'},
    { value:'Majherhat', label:'Majherhat'},
    { value:'Makardaha', label:'Makardaha'},
    { value:'Malancha Bazar', label:'Malancha Bazar'},
    { value:'Malancha Mahi Nagar', label:'Malancha Mahi Nagar'},
    { value:'Mandirtala', label:'Mandirtala'},
    { value:'Maniktala', label:'Maniktala'},
    { value:'Mankundu', label:'Mankundu'},
    { value:'Maslandapur', label:'Maslandapur'},
    { value:'Maula Ali', label:'Maula Ali'},
    { value:'Metiabruz', label:'Metiabruz'},
    { value:'Michael Nagar', label:'Michael Nagar'},
    { value:'Mominpore', label:'Mominpore'},
    { value:'Muchipara', label:'Muchipara'},
    { value:'Mukundapur', label:'Mukundapur'},
    { value:'Mullick Bazar', label:'Mullick Bazar'},
    { value:'Nabapally', label:'Nabapally'},
    { value:'Nadia', label:'Nadia'},
    { value:'Nagerbazar', label:'Nagerbazar'},
    { value:'Naihati', label:'Naihati'},
    { value:'Naktala', label:'Naktala'},
    { value:'Nandi Bagan', label:'Nandi Bagan'},
    { value:'Narayanpur', label:'Narayanpur'},
    { value:'Narendrapur', label:'Narendrapur'},
    { value:'Narkeldanga', label:'Narkeldanga'},
    { value:'Nayabad', label:'Nayabad'},
    { value:'Nazirabad', label:'Nazirabad'},
    { value:'Netaji Nagar', label:'Netaji Nagar'},
    { value:'Netaji Subhas Chandra Bose Road', label:'Netaji Subhas Chandra Bose Road'},
    { value:'New Alipore', label:'New Alipore'},
    { value:'New Barrakpur', label:'New Barrakpur'},
    { value:'New Garia', label:'New Garia'},
    { value:'New Town Action Area-I', label:'New Town Action Area-I'},
    { value:'New Town Action Area-II', label:'New Town Action Area-II'},
    { value:'New Town Action Area-III', label:'New Town Action Area-III'},
    { value:'Newtown', label:'Newtown'},
    { value:'Nimta', label:'Nimta'},
    { value:'Noapara', label:'Noapara'},
    { value:'North Dum Dum', label:'North Dum Dum'},
    { value:'Paikpara', label:'Paikpara'},
    { value:'Pailan', label:'Pailan'},
    { value:'Palta', label:'Palta'},
    { value:'Panchashyar', label:'Panchashyar'},
    { value:'Panditya Road', label:'Panditya Road'},
    { value:'Pandua', label:'Pandua'},
    { value:'Panihati', label:'Panihati'},
    { value:'Panpur', label:'Panpur'},
    { value:'Pansila', label:'Pansila'},
    { value:'Park Circus', label:'Park Circus'},
    { value:'Park Street Area', label:'Park Street Area'},
    { value:'Parnasree Pally', label:'Parnasree Pally'},
    { value:'Parui Mauza', label:'Parui Mauza'},
    { value:'Paschim Putiary', label:'Paschim Putiary'},
    { value:'Patipukur', label:'Patipukur'},
    { value:'Patuli', label:'Patuli'},
    { value:'Phulbagan', label:'Phulbagan'},
    { value:'Picnic Garden', label:'Picnic Garden'},
    { value:'Poddar Nagar', label:'Poddar Nagar'},
    { value:'Prince Anwar Shah Road', label:'Prince Anwar Shah Road'},
    { value:'Prince Anwar Shah Road Connector', label:'Prince Anwar Shah Road Connector'},
    { value:'Purba Barisha', label:'Purba Barisha'},
    { value:'Purba Putiari', label:'Purba Putiari'},
    { value:'Purbachal', label:'Purbachal'},
    { value:'Purbalok', label:'Purbalok'},
    { value:'Purna Das Road', label:'Purna Das Road'},
    { value:'Putuapara', label:'Putuapara'},
    { value:'Rabindra Nagar', label:'Rabindra Nagar'},
    { value:'Rabindra Sarani', label:'Rabindra Sarani'},
    { value:'Rabindrapally', label:'Rabindrapally'},
    { value:'Raghunathpur', label:'Raghunathpur'},
    { value:'Rahara', label:'Rahara'},
    { value:'Raichak', label:'Raichak'},
    { value:'Raja Bazar', label:'Raja Bazar'},
    { value:'Raja Ram Mohan Roy Road', label:'Raja Ram Mohan Roy Road'},
    { value:'Raja Rammohan Roy Sarani', label:'Raja Rammohan Roy Sarani'},
    { value:'Raja Subodh Chandra Mullick Road', label:'Raja Subodh Chandra Mullick Road'},
    { value:'Rajarhat', label:'Rajarhat'},
    { value:'Rajarhat Road', label:'Rajarhat Road'},
    { value:'Rajdanga Gardens', label:'Rajdanga Gardens'},
    { value:'Rajpur', label:'Rajpur'},
    { value:'Rajpur Chowhati', label:'Rajpur Chowhati'},
    { value:'Rajpur Sonarpur', label:'Rajpur Sonarpur'},
    { value:'Ram Bagan', label:'Ram Bagan'},
    { value:'Ramchandrapur', label:'Ramchandrapur'},
    { value:'Ramgarh', label:'Ramgarh'},
    { value:'Ramrajtala', label:'Ramrajtala'},
    { value:'Rasapunja', label:'Rasapunja'},
    { value:'Rash Behari Ave Connector', label:'Rash Behari Ave Connector'},
    { value:'Rash Behari Avenue', label:'Rash Behari Avenue'},
    { value:'Rathtala', label:'Rathtala'},
    { value:'Raypur', label:'Raypur'},
    { value:'Regent Estate', label:'Regent Estate'},
    { value:'Regent Park', label:'Regent Park'},
    { value:'Rekjuani', label:'Rekjuani'},
    { value:'Rishra', label:'Rishra'},
    { value:'Roy Bahadur Road', label:'Roy Bahadur Road'},
    { value:'Sahapur', label:'Sahapur'},
    { value:'Sakher Bazar', label:'Sakher Bazar'},
    { value:'Salkia', label:'Salkia'},
    { value:'Salt Lake City', label:'Salt Lake City'},
    { value:'Samali', label:'Samali'},
    { value:'Sankharipota', label:'Sankharipota'},
    { value:'Santoshpur', label:'Santoshpur'},
    { value:'Santragachi', label:'Santragachi'},
    { value:'Sarat Bose Road', label:'Sarat Bose Road'},
    { value:'Sarat Chatterjee Rd', label:'Sarat Chatterjee Rd'},
    { value:'Sarsuna', label:'Sarsuna'},
    { value:'Satgachhi', label:'Satgachhi'},
    { value:'Sealdah', label:'Sealdah'},
    { value:'Sector 3', label:'Sector 3'},
    { value:'Sector V', label:'Sector V'},
    { value:'Selimpur', label:'Selimpur'},
    { value:'Serampore', label:'Serampore'},
    { value:'Shibpur', label:'Shibpur'},
    { value:'Shobhabazar', label:'Shobhabazar'},
    { value:'Shyam Nagar', label:'Shyam Nagar'},
    { value:'Simla', label:'Simla'},
    { value:'Singur', label:'Singur'},
    { value:'Sinthee', label:'Sinthee'},
    { value:'Sodepur', label:'Sodepur'},
    { value:'Sonarpur', label:'Sonarpur'},
    { value:'South End Park', label:'South End Park'},
    { value:'Southern Avenue', label:'Southern Avenue'},
    { value:'Sreerampur', label:'Sreerampur'},
    { value:'Srinagar', label:'Srinagar'},
    { value:'Sripur', label:'Sripur'},
    { value:'Subhasgram', label:'Subhasgram'},
    { value:'Subhash Nagar', label:'Subhash Nagar'},
    { value:'Tagore Park', label:'Tagore Park'},
    { value:'Tala', label:'Tala'},
    { value:'Taltala', label:'Taltala'},
    { value:'Tangra', label:'Tangra'},
    { value:'Taratala', label:'Taratala'},
    { value:'Tegharia', label:'Tegharia'},
    { value:'Teghoria', label:'Teghoria'},
    { value:'Telipukur', label:'Telipukur'},
    { value:'Thakurpukur', label:'Thakurpukur'},
    { value:'Tikiapara', label:'Tikiapara'},
    { value:'Tiljala', label:'Tiljala'},
    { value:'Tiretti', label:'Tiretti'},
    { value:'Titagarh', label:'Titagarh'},
    { value:'Tollygunge', label:'Tollygunge'},
    { value:'Topsia', label:'Topsia'},
    { value:'Ultadanga', label:'Ultadanga'},
    { value:'Uluberia', label:'Uluberia'},
    { value:'Uttarpara', label:'Uttarpara'},
    { value:'VIP Nagar', label:'VIP Nagar'},
    { value:'VIP Road', label:'VIP Road'},
    { value:'Vivekananda Sarani', label:'Vivekananda Sarani'}
];